export const STEP_LIST_REQUEST = 'STEP_LIST_REQUEST'
export const STEP_LIST_SUCCESS = 'STEP_LIST_SUCCESS'
export const STEP_LIST_FAIL = 'STEP_LIST_FAIL'

export const STEP_HISTORY_REQUEST = 'STEP_HISTORY_REQUEST'
export const STEP_HISTORY_SUCCESS = 'STEP_HISTORY_SUCCESS'
export const STEP_HISTORY_FAIL = 'STEP_HISTORY_FAIL'

export const STEP_DETAILS_REQUEST = 'STEP_DETAILS_REQUEST'
export const STEP_DETAILS_SUCCESS = 'STEP_DETAILS_SUCCESS'
export const STEP_DETAILS_FAIL = 'STEP_DETAILS_FAIL'

export const STEP_DELETE_REQUEST = 'STEP_DELETE_REQUEST'
export const STEP_DELETE_SUCCESS = 'STEP_DELETE_SUCCESS'
export const STEP_DELETE_FAIL = 'STEP_DELETE_FAIL'

export const STEP_CREATE_REQUEST = 'STEP_CREATE_REQUEST'
export const STEP_CREATE_SUCCESS = 'STEP_CREATE_SUCCESS'
export const STEP_CREATE_FAIL = 'STEP_CREATE_FAIL'
export const STEP_CREATE_RESET = 'STEP_CREATE_RESET'

export const STEP_UPDATE_REQUEST = 'STEP_UPDATE_REQUEST'
export const STEP_UPDATE_SUCCESS = 'STEP_UPDATE_SUCCESS'
export const STEP_UPDATE_FAIL = 'STEP_UPDATE_FAIL'
export const STEP_UPDATE_RESET = 'STEP_UPDATE_RESET'

export const STEP_CREATE_REVIEW_REQUEST = 'STEP_CREATE_REVIEW_REQUEST'
export const STEP_CREATE_REVIEW_SUCCESS = 'STEP_CREATE_REVIEW_SUCCESS'
export const STEP_CREATE_REVIEW_FAIL = 'STEP_CREATE_REVIEW_FAIL'
export const STEP_CREATE_REVIEW_RESET = 'STEP_CREATE_REVIEW_RESET'

export const STEP_TOP_REQUEST = 'STEP_TOP_REQUEST'
export const STEP_TOP_SUCCESS = 'STEP_TOP_SUCCESS'
export const STEP_TOP_FAIL = 'STEP_TOP_FAIL'
