export const HISTORY_LIST_REQUEST = 'HISTORY_LIST_REQUEST'
export const HISTORY_LIST_SUCCESS = 'HISTORY_LIST_SUCCESS'
export const HISTORY_LIST_FAIL = 'HISTORY_LIST_FAIL'

export const HISTORY_MERCHANT_REQUEST = 'HISTORY_MERCHANT_REQUEST'
export const HISTORY_MERCHANT_SUCCESS = 'HISTORY_MERCHANT_SUCCESS'
export const HISTORY_MERCHANT_FAIL = 'HISTORY_MERCHANT_FAIL'

export const HISTORY_DETAILS_REQUEST = 'HISTORY_DETAILS_REQUEST'
export const HISTORY_DETAILS_SUCCESS = 'HISTORY_DETAILS_SUCCESS'
export const HISTORY_DETAILS_FAIL = 'HISTORY_DETAILS_FAIL'

export const HISTORY_DELETE_REQUEST = 'HISTORY_DELETE_REQUEST'
export const HISTORY_DELETE_SUCCESS = 'HISTORY_DELETE_SUCCESS'
export const HISTORY_DELETE_FAIL = 'HISTORY_DELETE_FAIL'

export const HISTORY_CREATE_REQUEST = 'HISTORY_CREATE_REQUEST'
export const HISTORY_CREATE_SUCCESS = 'HISTORY_CREATE_SUCCESS'
export const HISTORY_CREATE_FAIL = 'HISTORY_CREATE_FAIL'
export const HISTORY_CREATE_RESET = 'HISTORY_CREATE_RESET'

export const HISTORY_UPDATE_REQUEST = 'HISTORY_UPDATE_REQUEST'
export const HISTORY_UPDATE_SUCCESS = 'HISTORY_UPDATE_SUCCESS'
export const HISTORY_UPDATE_FAIL = 'HISTORY_UPDATE_FAIL'
export const HISTORY_UPDATE_RESET = 'HISTORY_UPDATE_RESET'

export const HISTORY_CREATE_REVIEW_REQUEST = 'HISTORY_CREATE_REVIEW_REQUEST'
export const HISTORY_CREATE_REVIEW_SUCCESS = 'HISTORY_CREATE_REVIEW_SUCCESS'
export const HISTORY_CREATE_REVIEW_FAIL = 'HISTORY_CREATE_REVIEW_FAIL'
export const HISTORY_CREATE_REVIEW_RESET = 'HISTORY_CREATE_REVIEW_RESET'

export const HISTORY_TOP_REQUEST = 'HISTORY_TOP_REQUEST'
export const HISTORY_TOP_SUCCESS = 'HISTORY_TOP_SUCCESS'
export const HISTORY_TOP_FAIL = 'HISTORY_TOP_FAIL'

export const HISTORY_PUBLICLIST_REQUEST = 'HISTORY_PUBLICLIST_REQUEST'
export const HISTORY_PUBLICLIST_SUCCESS = 'HISTORY_PUBLICLIST_SUCCESS'
export const HISTORY_PUBLICLIST_FAIL = 'HISTORY_PUBLICLIST_FAIL'
